import type { Metadata } from "next";
import { Darker_Grotesque, Inter_Tight } from "next/font/google";
import "./globals.css";
import {Header} from "../../components/Header";
import {Footer} from "../../components/Footer";

const darkGrotesque = Darker_Grotesque({
  variable: "--font-dark",
  subsets: ["latin"],
});

const interTight = Inter_Tight({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${darkGrotesque.variable} ${interTight.variable} antialiased`}
      >
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
